#!/usr/bin/env zsh

function with_suffix {
  number="$1"
  case $number in
    1?) echo "${number}th" ;;
    *1) echo "${number}st" ;;
    *2) echo "${number}nd" ;;
    *3) echo "${number}rd" ;;
    *)  echo "${number}th" ;;
  esac
}

function error {
  # print error result for Alfred
  cat << EOT
{
  "items": [
    {
      "title": "$1"
    }
  ]
}
EOT
  exit
}

query=${1:-"today"}

# trim whitespace
query=$(echo $query) 

# basic check for validity: must be 8 characters if it's numbers only
if [[ -z ${query//[0-9 ]/} && ${#query} -ne 8 ]] ; then
  error "Date format is invalid"
fi

# find day number for this date
result=$(gdate -d "$query" +%-j)
if [ $? -ne 0 ]; then
  error "Date cannot be parsed"
fi

# pretty print date and result
day=$(with_suffix $(gdate -d "$1" +%-e))
date=$(gdate -d "$1" "+%A $day %B %Y")

result_with_suffix=$(with_suffix $result)

# print result for Alfred
cat << EOT
{
  "items": [
    {
      "title": "$date is the $result_with_suffix day of the year",
      "subtitle": "Press enter to paste or ⌘C to copy",
      "arg": "$result"     
    }
  ]
}
EOT
