#!/usr/bin/env zsh

year=${1:-$(gdate "+%-Y")}

# Ensure year contains only digits and is no more than 4 digits long
if [[ -n ${year//[0-9]/} || ${#year} -gt 4 ]]; then
  cat << EOT
{
  "items": [
    {
      "title": "$1 is invalid"
    }
  ]
}
EOT
  exit
fi

# Zero pad years with less than 4 digits
query=$(printf "%04d" $query)

# If 31 March of $year is the 61st day, then it's a leap year
message="$year is not a leap year"
if [ $(gdate -d "$year-03-01" +%-j) -eq 61 ]; then
    message="$year is a leap year"
fi

# Print result for Alfred
cat << EOT
{
  "items": [
    {
      "title": "$message",
      "subtitle": "Press enter to paste or ⌘C to copy",
      "arg": "$message"     
    }
  ]
}
EOT
