name: Create Alfred Workflow

on:
  push:
    tags:
      - '[0-9].*'

permissions:
  contents: write      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Alfred workflow
        id: builder
        uses: almibarss/build-alfred-workflow@v1.1
        with:
          workflow_dir: .
          exclude_patterns: '.github/* .git/* .gitignore'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: ${{ steps.builder.outputs.workflow_file }}
